### ISSUE TITLE
Add custom card to v3

### ISSUE THREAD

**Issue by dkbay** [rasmus0201/planningpoker#12]
Please add custom card to v3!

**Comment by rasmus0201** [comment]
You're welcome to open a PR with your suggested feature!

**Comment by dkbay** [comment]
i cry 
<img width="160" alt="image" src="https://user-images.githubusercontent.com/1548975/217243409-651f6434-0335-4e7c-bbc1-8392644294aa.png">

**Comment by rasmus0201** [comment]
Fixed in https://github.com/rasmus0201/planningpoker/commit/a86104dd0cd63bdd62106377c17b44883403ac9d
